name: JS Learn App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - master
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        node_version:
          - 14
        architecture:
          - x64
    name: JS Learn App ${{ matrix.node_version }} - ${{ matrix.architecture }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}
      - run: npm ci
      - name: Test and Coverage
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.architecture }}
      - run: npm run coverage:ci
      - name: E2E Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
          record: true
          parallel: true
          start: npm start
        env:
          # pass the Dashboard record key as an environment variable
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}